version: '3.8'

services:
  Sondas:
    image: sondasapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./src:/app/src"
      - "./db:/app/db"
    environment:
      - PYTHONUNBUFFERED=1
    